name: Run PyAutoGUI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: |
          sudo apt update
          sudo apt install -y xvfb x11-utils xdotool xauth ffmpeg imagemagick xfce4-terminal
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest  # Instalar pytest

      - name: Configurar ambiente gráfico
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 &
          sleep 2  # Esperar o Xvfb estabilizar

          # Criar e configurar Xauthority manualmente
          touch ~/.Xauthority
          xauth generate :99 . trusted
          export XAUTHORITY=$HOME/.Xauthority

      - name: Criar diretório de relatórios
        run: mkdir -p reports

      - name: Iniciar gravação de tela
        run: |
          export DISPLAY=:99
          ffmpeg -y -f x11grab -video_size 1920x1080 -i :99 -r 25 -probesize 50M -analyzeduration 100M -pix_fmt yuv420p reports/test_recording.mp4 &
          echo $! > ffmpeg_pid.txt  # Salvar PID para encerrar depois
        shell: /usr/bin/bash -e {0}

      - name: Capturar tela inicial
        run: |
          export DISPLAY=:99
          import -window root reports/before_test.png
        shell: /usr/bin/bash -e {0}

      - name: Executar testes com PyAutoGUI
        run: |
          export DISPLAY=:99
          pytest ./tests -v --html=./reports/report.html --self-contained-html
        shell: /usr/bin/bash -e {0}

      - name: Encerrar gravação de tela
        run: |
          if [ -f ffmpeg_pid.txt ]; then
            kill $(cat ffmpeg_pid.txt) || true
          fi
        shell: /usr/bin/bash -e {0}

      - name: Upload do relatório de testes
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: reports/
