name: Run PyAutoGUI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y xclip 
          sudo apt install -y xvfb x11-utils xdotool xauth ffmpeg imagemagick python3-tk openbox 
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest pyautogui pyperclip Faker pytest-html 

      - name: Set up graphical environment
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 &
          sleep 5  # Espera o ambiente carregar
          
          touch ~/.Xauthority
          xauth generate :99 . trusted
          export XAUTHORITY=$HOME/.Xauthority
          
          openbox-session &
          sleep 2  # Espera Openbox carregar

          # Testa se o ambiente gráfico está funcionando
          xdotool mousemove 960 540 click 1
          
      - name: Create reports directory
        run: mkdir -p reports

      - name: Verify DISPLAY environment (Debugging)
        run: echo "DISPLAY is set to $DISPLAY"

      - name: Run tests with PyAutoGUI
        run: |
          export DISPLAY=:99

          # Inicia a gravação de vídeo aqui, dentro do teste
          ffmpeg -y -f x11grab -video_size 1920x1080 -i :99 -r 25 -probesize 50M -analyzeduration 100M -pix_fmt yuv420p reports/test_recording.mp4 &
          echo $! > ffmpeg_pid.txt  

          pytest ./tests -v --html=./reports/report.html --self-contained-html  

        shell: /usr/bin/bash -e {0}

      - name: Capture final screen
        run: |
          export DISPLAY=:99
          import -window root reports/final_test.png
        shell: /usr/bin/bash -e {0}

      - name: Stop screen recording
        run: |
          if [ -f ffmpeg_pid.txt ]; then
            kill $(cat ffmpeg_pid.txt) || true  
          fi
        shell: /usr/bin/bash -e {0}

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: reports/
