name: Test Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Instalar dependências
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb ffmpeg x11-utils
          pip install -r requirements.txt  # Instala as dependências do projeto
          pip install pytest-html  # Instalar o plugin do pytest para gerar HTML

      # Step 3: Configurar o servidor X virtual (Xvfb)
      - name: Start Xvfb
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 &  # Inicia o Xvfb em segundo plano
          sleep 2  # Aguarda um pouco para estabilizar

      # Step 4: Criar e configurar o Xauthority
      - name: Setup Xauthority
        run: |
          touch ~/.Xauthority
          xauth generate :99 . trusted
          export XAUTHORITY=$HOME/.Xauthority

      # Step 5: Iniciar a captura de tela com ffmpeg
      - name: Start screen capture with ffmpeg
        run: |
          export DISPLAY=:99
          ffmpeg -y -f x11grab -video_size 1920x1080 -i :99 -r 25 -probesize 50M -analyzeduration 100M -pix_fmt yuv420p reports/test_recording.mp4 &  # Inicia a captura de tela
          echo $! > ffmpeg_pid.txt  # Salva o PID do ffmpeg para encerrar depois

      # Step 6: Tirar uma captura de tela antes de rodar os testes
      - name: Capture screenshot before tests
        run: |
          export DISPLAY=:99
          import -window root reports/before_test.png

      # Step 7: Rodar os testes com pytest e gerar relatório HTML
      - name: Run tests with pytest
        run: |
          export DISPLAY=:99
          pytest ./tests -v --html=./reports/report.html --self-contained-html  # Rodar os testes e gerar o relatório HTML

      # Step 8: Finalizar a captura de tela com ffmpeg
      - name: Stop ffmpeg process
        run: |
          kill $(cat ffmpeg_pid.txt)  # Finaliza o processo ffmpeg

      # Step 9: Salvar artefatos de teste
      - name: Upload test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-artifacts
          path: reports/  # Salva os relatórios gerados (imagem e HTML)
